// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PasteleriaMG.Data.Contexts;

namespace PasteleriaMG.Data.Migrations
{
    [DbContext(typeof(PasteleriaMgDbContext))]
    [Migration("20201213192248_newModel")]
    partial class newModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PasteleriaMG.Data.Models.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellido1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apellido2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DireccionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DireccionId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("PasteleriaMG.Data.Models.Direccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Calle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodigoPostal")
                        .HasColumnType("int");

                    b.Property<Guid?>("LocalidadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProvinciaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LocalidadId");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Direccion");
                });

            modelBuilder.Entity("PasteleriaMG.Data.Models.IngredienteLimitante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IngredienteLimitante");
                });

            modelBuilder.Entity("PasteleriaMG.Data.Models.Localidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProvinciaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Localidad");
                });

            modelBuilder.Entity("PasteleriaMG.Data.Models.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoEntrega")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("PasteleriaMG.Data.Models.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdExterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoProducto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Producto");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Producto");
                });

            modelBuilder.Entity("PasteleriaMG.Data.Models.ProductoIngredienteLimitante", b =>
                {
                    b.Property<Guid>("IdProducto")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdIngredienteLimitante")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdProducto", "IdIngredienteLimitante");

                    b.HasIndex("IdIngredienteLimitante");

                    b.ToTable("ProductoIngredienteLimitante");
                });

            modelBuilder.Entity("PasteleriaMG.Data.Models.ProductoPedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<Guid?>("PedidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ProductoPedido");
                });

            modelBuilder.Entity("PasteleriaMG.Data.Models.Provincia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Provincia");
                });

            modelBuilder.Entity("PasteleriaMG.Data.Models.Pastel", b =>
                {
                    b.HasBaseType("PasteleriaMG.Data.Models.Producto");

                    b.HasDiscriminator().HasValue("Pastel");
                });

            modelBuilder.Entity("PasteleriaMG.Data.Models.Tarta", b =>
                {
                    b.HasBaseType("PasteleriaMG.Data.Models.Producto");

                    b.HasDiscriminator().HasValue("Tarta");
                });

            modelBuilder.Entity("PasteleriaMG.Data.Models.Cliente", b =>
                {
                    b.HasOne("PasteleriaMG.Data.Models.Direccion", "Direccion")
                        .WithMany()
                        .HasForeignKey("DireccionId");

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("PasteleriaMG.Data.Models.Direccion", b =>
                {
                    b.HasOne("PasteleriaMG.Data.Models.Localidad", "Localidad")
                        .WithMany()
                        .HasForeignKey("LocalidadId");

                    b.HasOne("PasteleriaMG.Data.Models.Provincia", "Provincia")
                        .WithMany()
                        .HasForeignKey("ProvinciaId");

                    b.Navigation("Localidad");

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("PasteleriaMG.Data.Models.Localidad", b =>
                {
                    b.HasOne("PasteleriaMG.Data.Models.Provincia", "Provincia")
                        .WithMany()
                        .HasForeignKey("ProvinciaId");

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("PasteleriaMG.Data.Models.Pedido", b =>
                {
                    b.HasOne("PasteleriaMG.Data.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("PasteleriaMG.Data.Models.ProductoIngredienteLimitante", b =>
                {
                    b.HasOne("PasteleriaMG.Data.Models.IngredienteLimitante", "IngredienteLimitante")
                        .WithMany("Productos")
                        .HasForeignKey("IdIngredienteLimitante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PasteleriaMG.Data.Models.Producto", "Producto")
                        .WithMany("IngredientesLimitantes")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngredienteLimitante");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("PasteleriaMG.Data.Models.ProductoPedido", b =>
                {
                    b.HasOne("PasteleriaMG.Data.Models.Pedido", null)
                        .WithMany("ProductosPedido")
                        .HasForeignKey("PedidoId");

                    b.HasOne("PasteleriaMG.Data.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("PasteleriaMG.Data.Models.IngredienteLimitante", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("PasteleriaMG.Data.Models.Pedido", b =>
                {
                    b.Navigation("ProductosPedido");
                });

            modelBuilder.Entity("PasteleriaMG.Data.Models.Producto", b =>
                {
                    b.Navigation("IngredientesLimitantes");
                });
#pragma warning restore 612, 618
        }
    }
}
